### PR TITLE
[doc] Add acceptance criteria for platform bots

### PR DESCRIPTION
**Pull request by acipm**
Developers should implement the specified minimal criterias

### CODE REVIEW

**Comment by m-rey** [comment]
Looks good to me!

**Comment by hagenest** [comment]
As someone who understands only about 10% of the code, the documentation seems a bit barebones. That is a problem on my side though.
I can't concisely formulate what I feel is missing, so I couldn't give any constructive criticism either.

**Comment by hagenest** [comment]
Further Question: Do we adhere to a certain markdown styling? 
Akin to https://github.com/markdownlint/markdownlint and it's vscode-counterpart https://github.com/DavidAnson/markdownlint.

**Comment by acipm** [comment]
> Further Question: Do we adhere to a certain markdown styling guideline?
> Akin to https://github.com/markdownlint/markdownlint and its vscode-counterpart https://github.com/DavidAnson/markdownlint.

Use the guideline that renders in pdoc3 for all docstrings that are not an REST API endpoint, for REST API endpoint docstrings use the guideline that renders in fastapi swagger doc.

**Comment by acipm** [comment]
> As someone who understands only about 10% of the code, the documentation seems a bit barebones. That is a problem on my side though.
> I can't concisely formulate what I feel is missing, so I wouldn't be able to give any constructive criticism either.
> Obviously the documentation is a great improvement compared to the existing one, with there being none. laughing
> Maybe I'm just spoiled by the totally awesome CONTRIBUTE.md.
> 
> Edit and slightly OT: Does GitHub want you to give a thumbs up somewhere, symboling that you're okay with the PR or does requesting a review just mean, that one of the chosen persons is asked to merge? Do I have to do something, to not be part of the pending reviewers? I think I'm too stupid to find the corresponding button.

I moved the documentation to the `CONTRIBUTING.md`, is it still too barebones for you? @maikeMai already wrote a good guide for the process and where to put files there and this checklist is just to be sure you did not miss anything.

**Pull request merged**
